### ISSUE TITLE
Instructions for security road-blocks

### ISSUE THREAD

**Issue by ramonck** [Zerg00s/Move-Lists#1]
Recommendations to add to instructions.

**Issue:** Windows Defender Smartscreen:
![image](https://user-images.githubusercontent.com/5229948/131664146-da4d8735-c473-4867-93e1-33e64d32d4cf.png)
1. Right click on the bat file you want to execute and open the Properties window from the contextual menu.
2. At the bottom of the "General" tab, you should see a "Security" section with an "Unblock" checkbox or button. Click on the button or check the box.
3. Click OK.
4. You should now be able to execute the BAT file without warning.

**Issue:** ps1 not digitally signed.
Run Powershell as administrator, run the following command:
```Set-ExecutionPolicy Unrestricted```

**Comment by Zerg00s** [comment]
@ramonck, thank you! I'll include your suggestions in the manual.

**Comment by Zerg00s** [comment]
@ramonck I've included your steps in the manual. Thank you!
