### ISSUE TITLE
Apply-PnPProvisioningTemplate : Value does not fall within the expected range.

### ISSUE THREAD

**Issue by oneillliam** [Zerg00s/Move-Lists#3]
Hi Denis,

I got this error when copying a list between two SharePoint Online sites on separate tenants using the latest version of Move-Lists.  I turned on Verbose error logging so hopefully the message below will help.  Best Regards  Liam

===========================================
Verbose test 25/05/22

C:\Users\littl\Downloads\Move-Lists (3)\
Verbose logging is on
PowerShell.exe Information: 0 : 2022-05-25 15:36:04.4167        [Extraction]    [10]    [Debug] Code execution scope started    0ms     1e7ca079-c5ac-40f4-b331-9fc220ed56d1                                                                    PowerShell.exe Information: 0 : 2022-05-25 15:36:04.4167        [Extraction]    [10]    [Debug] Base template available: GROUP0template 2ms     1e7ca079-c5ac-40f4-b331-9fc220ed56d1                                                            PowerShell.exe Information: 0 : 2022-05-25 15:36:04.4167        [Extraction]    [10]    [Debug] ProgressDelegate registered     2ms     1e7ca079-c5ac-40f4-b331-9fc220ed56d1                                                                    PowerShell.exe Information: 0 : 2022-05-25 15:36:04.4167        [Extraction]    [10]    [Debug] MessagesDelegate registered     2ms     1e7ca079-c5ac-40f4-b331-9fc220ed56d1                                                                    PowerShell.exe Information: 0 : 2022-05-25 15:36:04.6207        [Fields]        [10]    [Debug] Code execution scope started    7ms     1e7ca079-c5ac-40f4-b331-9fc220ed56d1
PowerShell.exe Information: 0 : 2022-05-25 15:36:10.0960        [Fields]        [10]    [Debug] Code execution scope ended      5495ms  1e7ca079-c5ac-40f4-b331-9fc220ed56d1
PowerShell.exe Information: 0 : 2022-05-25 15:36:10.1273        [Content Types] [10]    [Debug] Code execution scope started    0ms     1e7ca079-c5ac-40f4-b331-9fc220ed56d1
PowerShell.exe Information: 0 : 2022-05-25 15:36:11.3667        [Content Types] [10]    [Debug] Code execution scope ended      1229ms  1e7ca079-c5ac-40f4-b331-9fc220ed56d1
PowerShell.exe Information: 0 : 2022-05-25 15:36:11.4140        [List instances]        [10]    [Debug] Code execution scope started    0ms     1e7ca079-c5ac-40f4-b331-9fc220ed56d1
PowerShell.exe Information: 0 : 2022-05-25 15:36:17.2980        [Get Security]  [10]    [Debug] Code execution scope started    0ms     1e7ca079-c5ac-40f4-b331-9fc220ed56d1
PowerShell.exe Information: 0 : 2022-05-25 15:36:17.3921        [Get Security]  [10]    [Debug] Code execution scope ended      103ms   1e7ca079-c5ac-40f4-b331-9fc220ed56d1
PowerShell.exe Information: 0 : 2022-05-25 15:36:17.5180        [List instances]        [10]    [Debug] Adding list: Area - Lists/Area2 6109ms  1e7ca079-c5ac-40f4-b331-9fc220ed56d1
PowerShell.exe Information: 0 : 2022-05-25 15:36:17.5180        [List instances]        [10]    [Debug] Code execution scope ended      6109ms  1e7ca079-c5ac-40f4-b331-9fc220ed56d1
PowerShell.exe Information: 0 : 2022-05-25 15:36:17.5336        [Retrieve Template Info]        [10]    [Debug] Code execution scope started    0ms     1e7ca079-c5ac-40f4-b331-9fc220ed56d1
PowerShell.exe Information: 0 : 2022-05-25 15:36:17.7069        [Retrieve Template Info]        [10]    [Debug] Code execution scope ended      177ms   1e7ca079-c5ac-40f4-b331-9fc220ed56d1
PowerShell.exe Information: 0 : 2022-05-25 15:36:17.7069        [Extraction]    [10]    [Debug] Code execution scope ended      13292ms 1e7ca079-c5ac-40f4-b331-9fc220ed56d1
PowerShell.exe Information: 0 : 2022-05-25 15:36:17.9103        [OfficeDevPnP.Core]     [0]     [Information]   File C:\Users\littl\Downloads\Move-Lists (3)\Lists.xml saved to folder  0ms
PowerShell.exe Error: 0 : 2022-05-25 15:36:25.4233      [OfficeDevPnP.Core]     [0]     [Error] ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: Current site is not a tenant administration site.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---                                               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()                                                       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)                       at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()                               --- End of stack trace from previous location where exception was thrown ---                                               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()                                                       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)                       at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()                                      --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
ServerErrorCode: -1
ServerErrorTypeName: Microsoft.Online.SharePoint.Common.SpoException
ServerErrorTraceCorrelationId: 29dd40a0-b0a9-4000-0d3c-69b54a12434a
ServerErrorValue:                                                                                                       ServerErrorDetails:                                                                                                     .       0ms                                                                                                             PowerShell.exe Information: 0 : 2022-05-25 15:36:25.5567        [OfficeDevPnP.Core]     [0]     [Information]   File Lists.xml retrieved from folder    0ms                                                                                     PowerShell.exe Information: 0 : 2022-05-25 15:36:25.5567        [OfficeDevPnP.Core]     [0]     [Information]   File Lists.xml retrieved from folder    0ms                                                                                     PowerShell.exe Information: 0 : 2022-05-25 15:36:25.6238        [Provisioning]  [10]    [Debug] Code execution scope started    0ms     400701ff-0219-40d8-b467-7672779308b0                                                                    PowerShell.exe Information: 0 : 2022-05-25 15:36:25.6238        [Provisioning]  [10]    [Information]   ProgressDelegate registered     0ms     400701ff-0219-40d8-b467-7672779308b0                                                            PowerShell.exe Information: 0 : 2022-05-25 15:36:25.6238        [Provisioning]  [10]    [Information]   MessagesDelegate registered     1ms     400701ff-0219-40d8-b467-7672779308b0                                                            PowerShell.exe Information: 0 : 2022-05-25 15:36:27.1116        [Extensibility Providers]       [10]    [Debug] Code execution scope started    0ms     400701ff-0219-40d8-b467-7672779308b0                                                    PowerShell.exe Information: 0 : 2022-05-25 15:36:27.1116        [Extensibility Providers]       [10]    [Debug] Code execution scope ended      0ms     400701ff-0219-40d8-b467-7672779308b0                                                    PowerShell.exe Information: 0 : 2022-05-25 15:36:27.1428        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope started     0ms     400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:27.1428        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope ended       0ms     400701ff-0219-40d8-b467-7672779308b0                                            PowerShell.exe Information: 0 : 2022-05-25 15:36:27.1584        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope started     0ms     400701ff-0219-40d8-b467-7672779308b0                                            PowerShell.exe Information: 0 : 2022-05-25 15:36:27.1584        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope ended       0ms     400701ff-0219-40d8-b467-7672779308b0                                            PowerShell.exe Information: 0 : 2022-05-25 15:36:27.1740        [Fields]        [10]    [Debug] Code execution scope started    0ms     400701ff-0219-40d8-b467-7672779308b0                                                                    PowerShell.exe Information: 0 : 2022-05-25 15:36:27.4722        [Fields]        [10]    [Debug] Updating field {9889a80f-c9ec-41d8-a359-ac5fb5c4cfa2} in site   293ms   400701ff-0219-40d8-b467-7672779308b0                                    PowerShell.exe Information: 0 : 2022-05-25 15:36:27.5351        [Fields]        [10]    [Debug] Updating field {cb19284a-cde7-4570-a980-1dab8bd74470} in site   369ms   400701ff-0219-40d8-b467-7672779308b0                                    PowerShell.exe Information: 0 : 2022-05-25 15:36:27.6133        [Fields]        [10]    [Debug] Updating field {08D89A66-4634-42B8-9D5A-0C27395A48B3} in site   440ms   400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:27.6762        [Fields]        [10]    [Debug] Updating field {ff41708b-e251-4237-a060-bea44657e8dc} in site   507ms   400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:27.7547        [Fields]        [10]    [Debug] Code execution scope ended      577ms   400701ff-0219-40d8-b467-7672779308b0                                                                    PowerShell.exe Information: 0 : 2022-05-25 15:36:27.7703        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope started     0ms     400701ff-0219-40d8-b467-7672779308b0                                            PowerShell.exe Information: 0 : 2022-05-25 15:36:27.7703        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope ended       0ms     400701ff-0219-40d8-b467-7672779308b0                                            PowerShell.exe Information: 0 : 2022-05-25 15:36:27.7703        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope started     0ms     400701ff-0219-40d8-b467-7672779308b0                                            PowerShell.exe Information: 0 : 2022-05-25 15:36:27.7703        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope ended       0ms     400701ff-0219-40d8-b467-7672779308b0                                            PowerShell.exe Information: 0 : 2022-05-25 15:36:27.7860        [List instances]        [10]    [Debug] Code execution scope started    0ms     400701ff-0219-40d8-b467-7672779308b0                                                            PowerShell.exe Information: 0 : 2022-05-25 15:36:27.9431        [List instances]        [10]    [Debug] Creating list Area      149ms   400701ff-0219-40d8-b467-7672779308b0                                                                    PowerShell.exe Information: 0 : 2022-05-25 15:36:31.3639        [List instances]        [10]    [Debug] Creating field a4d982c2-9de3-430b-ad5c-a7a75a41ad9e     3579ms  400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:31.5206        [List instances]        [10]    [Debug] Code execution scope ended      3724ms  400701ff-0219-40d8-b467-7672779308b0                                                            PowerShell.exe Information: 0 : 2022-05-25 15:36:31.5206        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope started     0ms     400701ff-0219-40d8-b467-7672779308b0                                            PowerShell.exe Information: 0 : 2022-05-25 15:36:31.5206        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope ended       0ms     400701ff-0219-40d8-b467-7672779308b0                                            PowerShell.exe Information: 0 : 2022-05-25 15:36:31.5206        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope started     0ms     400701ff-0219-40d8-b467-7672779308b0                                            PowerShell.exe Information: 0 : 2022-05-25 15:36:31.5206        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope ended       0ms     400701ff-0219-40d8-b467-7672779308b0                                            PowerShell.exe Information: 0 : 2022-05-25 15:36:31.5206        [Fields]        [10]    [Debug] Code execution scope started    0ms     400701ff-0219-40d8-b467-7672779308b0                                                                    PowerShell.exe Information: 0 : 2022-05-25 15:36:31.6148        [Fields]        [10]    [Debug] Updating field {AC9CE95B-F081-4B8A-BB19-2F4427D44674} in site   86ms    400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:31.6933        [Fields]        [10]    [Debug] Updating field {3A8EE3F8-166B-4394-B3E2-E98DCF86A847} in site   165ms   400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:31.7406        [Fields]        [10]    [Debug] Code execution scope ended      215ms   400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:31.7562        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope started     0ms     400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:31.7562        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope ended       0ms     400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:31.7719        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope started     0ms     400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:31.7719        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope ended       0ms     400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:31.7719        [List instances]        [10]    [Debug] Code execution scope started    0ms     400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:31.8973        [List instances]        [10]    [Debug] Updating list Area      121ms   400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Warning: 0 : 2022-05-25 15:36:32.0382    [List instances]        [10]    [Information]   Skip adding/updating custom actions because the site has "noscript" enabled.    268ms   400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:32.1164        [List instances]        [10]    [Debug] Creating field 0939d1dc-e0a4-43d5-a773-195a965e8ff9     350ms   400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Error: 0 : 2022-05-25 15:36:32.2422      [OfficeDevPnP.Core]     [0]     [Error] ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: File Not Found.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
ServerErrorCode: -2147024894
ServerErrorTypeName: System.IO.FileNotFoundException
ServerErrorTraceCorrelationId: 2bdd40a0-8052-4000-0d3c-640482c6d035
ServerErrorValue:
ServerErrorDetails:
.       0ms
PowerShell.exe Error: 0 : 2022-05-25 15:36:32.2891      [OfficeDevPnP.Core]     [0]     [Error] ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: Value does not fall within the expected range.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
ServerErrorCode: -2147024809
ServerErrorTypeName: System.ArgumentException
ServerErrorTraceCorrelationId: 2bdd40a0-e057-4000-0d3c-651904d8e3f5
ServerErrorValue:
ServerErrorDetails:
.       0ms
PowerShell.exe Error: 0 : 2022-05-25 15:36:32.2891      [List instances]        [10]    [Error] Creating field 0939d1dc-e0a4-43d5-a773-195a965e8ff9 failed: Value does not fall within the expected range. :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateField(XElement fieldElement, ListInfo listInfo, TokenParser parser, String originalFieldXml, ClientContext context, PnPMonitoredScope scope)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProcessFields(Web web, TokenParser parser, PnPMonitoredScope scope, ListInfo listInfo) 520ms   400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:32.3047        [List instances]        [10]    [Debug] Code execution scope ended      530ms   400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:32.3047        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope started     0ms     400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:32.3047        [ProvisioningTemplate WebHook Call]     [10]    [Debug]Code execution scope ended       0ms     400701ff-0219-40d8-b467-7672779308b0
PowerShell.exe Information: 0 : 2022-05-25 15:36:32.3047        [Provisioning]  [10]    [Debug] Code execution scope ended      6687ms  400701ff-0219-40d8-b467-7672779308b0
Apply-PnPProvisioningTemplate : Value does not fall within the expected range.
At C:\Users\littl\Downloads\Move-Lists (3)\Move-Lists.ps1:84 char:1
+ Apply-PnPProvisioningTemplate -Path Lists.xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate

C:\WINDOWS\system32>PAUSE
Press any key to continue . . .

**Comment by Zerg00s** [comment]
Hi @oneillliam. Thank you for the trace logs. I can see the error message, but it's quite weird:

> Microsoft.SharePoint.Client.ServerException: Current site is not a tenant administration site.

Would you be able to share the **Lists.xml** file from the script folder? I might be able to try to test this XML template against my Dev SPO site to see what is wrong with it.

**Comment by oneillliam** [comment]
Thanks Denis - here is the XML file....

[Listsxml.txt](https://github.com/Zerg00s/Move-Lists/files/8777064/Listsxml.txt)

**Comment by Zerg00s** [comment]
Hi @oneillliam,

Thank you for the XML file. The list you are migrating contains lookup fields that are not yet supported for migration:
- Facility
- Floor
- Zone
- Area

![image](https://user-images.githubusercontent.com/2797648/170501670-bf0b57e3-e0f1-4411-ba78-6f2116b2206a.png)

However, can you, please, try this experiment for me? Run the Move-Lists script again, and instead of just one list, select all 5 lists.
- Call To Action
- Facility
- Floor
- Zone
- Area

It _might_ work, but I can't guarantee it...

If that does not work, you can do the following:
- Open the Lists.XML file
- Remove The Facility, Floor, Zone and Area fields from the XML, from the **ViewFields** and **pnp:Fields** nodes:

```
<ViewFields>
  <FieldRef Name="LinkTitle"/>
  <FieldRef Name="Description"/>
  <FieldRef Name="ID"/>
  <FieldRef Name="Facility"/> 
  <FieldRef Name="Floor"/>
  <FieldRef Name="Zone"/>
  <FieldRef Name="Area"/>
</ViewFields>
```

```
<pnp:Fields>
  <Field AppendOnly="FALSE" DisplayName="Description" Format="Dropdown" IsModern="TRUE" IsolateStyles="FALSE" Name="Description" RichText="FALSE" RichTextMode="Compatible" Title="Description" Type="Note" ID="{bbb1553a-e783-4b64-9441-ed28dd9ebd12}" SourceID="{{listid:Desk}}" StaticName="Description" ColName="ntext2" RowOrdinal="0"/>
  <Field Type="Lookup" DisplayName="Facility" Required="FALSE" EnforceUniqueValues="FALSE" List="{listid:Facility}" ShowField="Title" UnlimitedLengthInDocumentLibrary="FALSE" RelationshipDeleteBehavior="None" ID="{6f005707-e448-4cd8-94c9-77284d2f468e}" SourceID="{{listid:Desk}}" StaticName="Facility" Name="Facility" ColName="int1" RowOrdinal="0"/>
  <Field Type="Lookup" DisplayName="Floor" Required="FALSE" EnforceUniqueValues="FALSE" List="{listid:Floor}" ShowField="Title" UnlimitedLengthInDocumentLibrary="FALSE" RelationshipDeleteBehavior="None" ID="{c53a90dc-5ff4-4d6d-9ef5-9fe89c89a8a6}" SourceID="{{listid:Desk}}" StaticName="Floor" Name="Floor" ColName="int2" RowOrdinal="0"/>
  <Field Type="Lookup" DisplayName="Zone" Required="FALSE" EnforceUniqueValues="FALSE" List="{listid:Zone}" ShowField="Title" UnlimitedLengthInDocumentLibrary="FALSE" RelationshipDeleteBehavior="None" ID="{f00ae02b-113f-4722-a8d3-658e1f0a5ca6}" SourceID="{{listid:Desk}}" StaticName="Zone" Name="Zone" ColName="int3" RowOrdinal="0"/>
  <Field Type="Lookup" DisplayName="Area" Required="FALSE" EnforceUniqueValues="FALSE" List="{listid:Area}" ShowField="ID" UnlimitedLengthInDocumentLibrary="FALSE" RelationshipDeleteBehavior="None" ID="{4e3f41a3-affc-425a-91fb-67a19dcde3b8}" SourceID="{{listid:Desk}}" StaticName="Area" Name="Area" ColName="int4" RowOrdinal="0"/>
</pnp:Fields>
```

Then run the code:

```
cd "C:\Move-Lists\"
Connect-PnPOnline -Url https://YOUR_SITE.sharepoint.com  -UseWebLogin
Apply-PnPProvisioningTemplate -Path .\Lists.xml
```

Then navigate to the **Call To Action* list and* add these 4 lookup fields manually:
- Facility
- Floor
- Zone
- Area

**Comment by oneillliam** [comment]
Hi Denis

I tried the experiment and delighted to report it worked!

Thanks very much.

**Comment by Zerg00s** [comment]
Ah! nice. Thani you for trying it! I will document this solution 😊

**Comment by Zerg00s** [comment]
Issue can be resolved by selecting lookup lists at the same time as the main list during the migration.
